mod_2/rails-intro/config/routes.rb
Rails.application.routes.draw do
  resources :cavemen
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :dinosaurs
end

mod_2/rails-intro/app/models/caveman.rb
class Caveman < ApplicationRecord
end

mod_2/rails-intro/app/models/dinosaur.rb
class Dinosaur < ApplicationRecord
end

mod_2/rails-intro/app/controllers/cavemen_controller.rb
class CavemenController < ApplicationController
end

mod_2/rails-intro/app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  def index
    @dinosaurs = Dinosaur.all
  end

  def show
    @dinosaur = Dinosaur.find_by(id: params[:id])
  end

  def edit

  end

  def new
    # if we want to use rails form builder methods like form_for,
    # we have to provide an instance of the model we're building
    @dinosaur = Dinosaur.new
  end

  def create
    new_dino = Dinosaur.new(dino_params)

    if new_dino.save
      redirect_to dinosaur_path(new_dino)
    else
      render :new
    end
  end

  private

  def dino_params
    params.require(:dinosaur).permit(:name, :species, :number_of_teeth, :era, :diet)
  end
end

mod_2/rails-intro/app/helpers/cavemen_helper.rb
module CavemenHelper
end

mod_2/rails-intro/app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

mod_2/rails-intro/app/views/dinosaurs/index.html.erb
<p id="notice"><%= notice %></p>

<ul>

<% @dinosaurs.each do |dino| %>
  <li><strong><%= dino.name %></strong></li>
  <li><%= dino.era %></li>
  <li><%= dino.species %></li>
  <li><%= dino.number_of_teeth %></li>
<% end %>
</ul>

mod_2/rails-intro/app/views/dinosaurs/new.html.erb
<%# Here are three ways to do the same thing %>
<%# Notice the differences between vanilla html, form_tag, and form_for %>
<%# The diversion from REST is just so we can show how we might handle %>
<%# the form's POST request in each case %>


<%# Let's start with vanilla HTML.  The only unfamiliar part of this  %>
<%# should be the auth token.  Rails comes with some built-in form  %>
<%# security.  Basically, when the server generates a form it gives it  %>
<%# a unique authorization token.  If the form doesn't return that  %>
<%# token when it's submitted, rails will reject the request.  %>
<h3>Old School</h3>
<form action="/dinosaurs" method="post">
  <input type="hidden" name="authenticity_token" value="token_value">
  <input type="text" name="dinosaur[name]" placeholder="name">
  <input type="text" name="dinosaur[number_of_teeth]" placeholder="number of teeth">
  <input type="text" name="dinosaur[species]" placeholder="species">
  <input type="text" name="dinosaur[diet]" placeholder="diet">
  <input type="text" name="dinosaur[era]" placeholder="era">
  <input type="submit" value="create dino">
</form>

<h3>Form Tag</h3>
<%# Next, let's use form_tag helper method %>
<%# form_tag and form_for will auto-gen the auth token for us %>
<%= form_tag "/dinosaurs" do %>
  <%= text_field_tag "dinosaur[name]", "", placeholder: "name" %>
  <%= text_field_tag "dinosaur[number_of_teeth]", "", placeholder: "number_of_teeth"  %>
  <%= text_field_tag "dinosaur[species]", "", placeholder: "species"  %>
  <%= text_field_tag "dinosaur[diet]", "", placeholder: "diet"  %>
  <%= text_field_tag "dinosaur[era]", "", placeholder: "era"  %>
  <%= submit_tag "create dino" %>
<% end %>


<h3>Form For</h3>
<%# Finally, let's use form_for, which builds a form around a given object %>
<%# Also notice that the params automatically get namespaced under dinosaur %>
<%= form_for @dinosaur do |f| %>
  <%= f.text_field :name, placeholder: "name" %>
  <%= f.text_field :number_of_teeth, placeholder: "number_of_teeth" %>
  <%= f.text_field :species, placeholder: "species" %>
  <%= f.text_field :diet, placeholder: "diet" %>
  <%= f.text_field :era, placeholder: "era" %>
  <%= f.submit "create dino" %>
<% end %>

mod_2/rails-intro/app/views/dinosaurs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>I'm <%= @dinosaur.name %></h1>

mod_2/rails-intro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "all dinos", dinosaurs_path %> <br>
    <%= link_to "make a new dino", new_dinosaur_path%> <br>
    <%= yield %>
  </body>
</html>